name: Build Glazed

on:
  workflow_dispatch:
  push:
    branches:
      - 1.21.11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Glazed-JAR
          path: build/libs/*.jar
